version: 2.1
jobs:
  build-run:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

workflows:
  default:
    jobs:
      - build-run
